### ISSUE TITLE
Wildcard imports are removed

### ISSUE THREAD

**Issue by leighmcculloch** [akhaku/vim-java-unused-imports#19]
Wildcard imports are removed even when they are being used. The plugin should probably ignore wildcard imports since it's difficult to determine if they're being used. I'd be happy to attempt to make a change to support this.

**Comment by akhaku** [comment]
Sounds good to me, I'd love a PR! I tend to avoid star imports myself so haven't run into it

**Comment by mrmrsbeck1617** [comment]
?
________________________________

**Comment by mrmrsbeck1617** [comment]
im havin trying to understand.. a tough time

**Comment by mrmrsbeck1617** [comment]
i meant im having a tougg time
________________________________

**Comment by mrmrsbeck1617** [comment]
imoff work next two days if thats what you meant
________________________________

**Comment by mrmrsbeck1617** [comment]
i aint blaming novody for what i e done
________________________________

**Comment by mrmrsbeck1617** [comment]
just didnt want to bring shit down here or to tiffanys
________________________________

**Comment by mrmrsbeck1617** [comment]
see u tom
________________________________

**Comment by leighmcculloch** [comment]
@akhaku I opened a fix in #20. How does that look to you?
